//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public long ID { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<long> CANTIDAD { get; set; }
        public Nullable<long> ID_PEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
