//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public long ID { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<long> CANTIDAD { get; set; }
        public Nullable<long> ID_PEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
