//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
=======
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> master
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        public HABITACION()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public long NUMERO { get; set; }
        public string TIPO { get; set; }
        public Nullable<long> CAMAS { get; set; }
        public Nullable<long> PRECIO { get; set; }
<<<<<<< HEAD
        public Nullable<short> DISPONIBLE { get; set; }
=======
>>>>>>> master
    
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
    }
}
