//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO
    {
        public long ID { get; set; }
        public string NOMBRE { get; set; }
        public long ID_SERVICIO { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
