//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIVILEGIO
    {
        public decimal ID { get; set; }
        public string MENU { get; set; }
        public Nullable<decimal> CREATE { get; set; }
        public Nullable<decimal> READ { get; set; }
        public Nullable<decimal> UPDATE { get; set; }
        public Nullable<decimal> DELETE { get; set; }
        public Nullable<decimal> USUARIO_ID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
