//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIVILEGIO
    {
        public decimal ID { get; set; }
        public string MENU { get; set; }
        public Nullable<decimal> CREATE { get; set; }
        public Nullable<decimal> READ { get; set; }
        public Nullable<decimal> UPDATE { get; set; }
        public Nullable<decimal> DELETE { get; set; }
        public Nullable<decimal> USUARIO_ID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
