//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string RUBRO { get; set; }
        public decimal USUARIO_ID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
