//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
            this.PLATO = new HashSet<PLATO>();
        }
    
        public long ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<long> PRECIO { get; set; }
    
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
